routes/web.php
<?php

use App\Http\Controllers\Admin\BannerController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ColorController;
use App\Http\Controllers\Admin\ConfigController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\SizeController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Shopping\CartController;
use App\Http\Controllers\Shopping\CheckoutController;
use App\Http\Controllers\Shopping\OrderController as SOC;
use App\Http\Controllers\Shopping\ShoppingController;
use App\Http\Controllers\Shopping\WishlistController;
use App\Http\Controllers\Shopping\UserController as SUC;
use App\Http\Livewire\Admin\Brand\Index;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\URL;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

if (App::environment('production')) {
    URL::forceScheme('https');
}

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::controller(ShoppingController::class)->group(function () {
    Route::get('/', 'index')->name('shopping');
    Route::get('/search', 'search')->name('search');
    Route::get('/category', 'category')->name('category');
    Route::get('/category/{slug}', 'catalogProduct')->name('category.product');
    Route::get('/product/{category}/{slug}', 'productDetail')->name('product.detail');
    Route::get('/trending-product', 'trendingProduct')->name('trending.product');
    Route::get('/new-arrival', 'newArrival')->name('new.arrival');
    Route::get('/featured-product', 'featuredProduct')->name('featured.product');
    Route::get('/thank-you', 'thankyou')->name('thank.you');
});

Route::middleware('auth')->group(function () {
    Route::get('/wishlist', [WishlistController::class, 'index'])->name('wishlist');
    Route::get('/cart', [CartController::class, 'index'])->name('cart');
    Route::get('/checkout', [CheckoutController::class, 'index'])->name('checkout');
    Route::get('/order', [SOC::class, 'index'])->name('order.index');
    Route::get('/order/{order}', [SOC::class, 'show'])->name('order.show');
    Route::get('/profile', [SUC::class, 'index'])->name('profile.index');
    Route::post('/profile', [SUC::class, 'store'])->name('profile.store');
    Route::get('/password', [SUC::class, 'show'])->name('password.create');
    Route::post('/password', [SUC::class, 'update'])->name('password.change');
});

Route::prefix('/admin')->middleware(['auth', 'isAdmin'])->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('admin.dashboard');

    Route::get('/brands', Index::class)->name('brands.index');

    Route::prefix('/configs')->controller(ConfigController::class)->name('configs.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::post('/store', 'store')->name('store');
    });

    Route::prefix('/orders')->controller(OrderController::class)->name('orders.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/{order}', 'show')->name('show');
        Route::put('/{order}', 'update')->name('update');
        Route::get('/invoice/show/{id}', 'display')->name('invoice.display');
        Route::get('/invoice/generate/{id}', 'generate')->name('invoice.generate');
        Route::get('/invoice/send/{id}', 'send')->name('invoice.send');
    });

    Route::prefix('/banners')->controller(BannerController::class)->name('banners.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/create', 'create')->name('create');
        Route::post('/store', 'store')->name('store');
        Route::get('/{banner}/edit', 'edit')->name('edit');
        Route::put('/{banner}/update', 'update')->name('update');
        Route::get('/{banner}/delete', 'destroy')->name('destroy');
    });

    Route::prefix('/categories')->controller(CategoryController::class)->name('categories.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/create', 'create')->name('create');
        Route::post('/store', 'store')->name('store');
        Route::get('/{category}/edit', 'edit')->name('edit');
        Route::put('/{category}/update', 'update')->name('update');
    });

    Route::prefix('/products')->controller(ProductController::class)->name('products.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/create', 'create')->name('create');
        Route::post('/store', 'store')->name('store');
        Route::get('/{product}/edit', 'edit')->name('edit');
        Route::put('/{product}/update', 'update')->name('update');
        Route::post('/{product}/color', 'updateColorQuantity')->name('updateColorQuantity');
        Route::post('/{product}/size', 'updateSizeQuantity')->name('updateSizeQuantity');
        Route::get('/{product}/color/delete', 'removeColor')->name('removeColor');
        Route::get('/{product}/size/delete', 'removeSize')->name('removeSize');
        Route::get('/{product}/image', 'remove')->name('remove');
        Route::get('/{product}/delete', 'destroy')->name('destroy');
    });

    Route::prefix('/colors')->controller(ColorController::class)->name('colors.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/create', 'create')->name('create');
        Route::post('/store', 'store')->name('store');
        Route::get('/{color}/edit', 'edit')->name('edit');
        Route::put('/{color}/update', 'update')->name('update');
        Route::get('/{color}/delete', 'destroy')->name('destroy');
    });

    Route::prefix('/sizes')->controller(SizeController::class)->name('sizes.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/create', 'create')->name('create');
        Route::post('/store', 'store')->name('store');
        Route::get('/{size}/edit', 'edit')->name('edit');
        Route::put('/{size}/update', 'update')->name('update');
        Route::get('/{size}/delete', 'destroy')->name('destroy');
    });

    Route::prefix('/users')->controller(UserController::class)->name('users.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/create', 'create')->name('create');
        Route::post('/store', 'store')->name('store');
        Route::get('/{user}/edit', 'edit')->name('edit');
        Route::put('/{user}/update', 'update')->name('update');
        Route::get('/{user}/delete', 'destroy')->name('destroy');
    });
});

app/Models/Color.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Color extends Model
{
    use HasFactory;

    protected $table = 'colors';

    protected $fillable = ['name', 'code', 'status'];
}

app/Http/Controllers/Admin/ColorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Color\ColorFormRequest;
use App\Models\Color;
use Illuminate\Http\Request;

class ColorController extends Controller
{
    /**
     * @var Color $color
     */
    protected Color $color;

    /**
     * Create a new controller instance.
     *
     * @param Color $color
     */
    public function __construct(Color $color)
    {
        $this->color = $color;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $colors = $this->color->latest('id')->paginate(5);
        return view('admin.colors.index', compact('colors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.colors.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  ColorFormRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(ColorFormRequest $request)
    {
        $validatedData = $request->validated();
        $validatedData['status'] = $request->status ? '1' : '0';
        $color = $this->color->create($validatedData);
        return redirect()->route('colors.index')->with('message', 'Color '.$color->name.' has already created successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Color  $color
     * @return \Illuminate\Http\Response
     */
    public function show(Color $color)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Color  $color
     * @return \Illuminate\Http\Response
     */
    public function edit(Color $color)
    {
        return view('admin.colors.edit', compact('color'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  integer $id
     * @return \Illuminate\Http\Response
     */
    public function update(ColorFormRequest $request, int $id)
    {
        $validatedData = $request->validated();
        $validatedData['status'] = $request->status ? '1' : '0';
        $color = $this->color->findOrFail($id);
        $color->update($validatedData);
        return redirect()->route('colors.index')->with('message', 'Color '.$color->name.' has already updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  integer $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(int $id)
    {
        $color = $this->color->findOrFail($id);
        $color->delete();
        return redirect()->route('colors.index')->with('message', 'This color has already deleted successfully!');
    }
}

resources/views/admin/colors/create.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="main-panel">
        <!-- content-wrapper start -->
        <div class="content-wrapper">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="d-flex justify-content-between align-items-center">
                                <span class="text-uppercase">Add Color</span>
                                <a href="{{route('colors.index')}}" class="btn btn-outline-secondary">BACK</a>
                            </h3>
                        </div>
                        <form method="POST" enctype="multipart/form-data" action="{{route('colors.store')}}">
                            @csrf
                            <div class="card-body">
                                <div class="form-group mb-3">
                                    <label for="name">Color Name</label>
                                    <input class="form-control" id="name" name="name" value="{{old('name')}}" autofocus>
                                    @error('name') <span class="text-danger">{{$message}}</span> @enderror
                                </div>

                                <div class="form-group mb-3">
                                    <label for="code">Color Code</label>
                                    <input class="form-control" id="code" name="code" value="{{old('code')}}" autofocus>
                                    @error('code') <span class="text-danger">{{$message}}</span> @enderror
                                </div>

                                <div class="form-group mb-3">
                                    <label for="status">Status</label>
                                    <input type="checkbox" class="form-check" id="status" name="status" style="width: 30px;height: 30px;">
                                </div>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-outline-primary">SUBMIT</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper end -->

        <!-- Start footer -->
        <footer class="footer">
            <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright ©
                <a href="https://www.bootstrapdash.com/" target="_blank">bootstrapdash.com </a>2021
            </span>
                <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Only the best
                <a href="https://www.bootstrapdash.com/" target="_blank"> Bootstrap dashboard  </a> templates
            </span>
            </div>
        </footer>
        <!-- End footer -->
    </div>
@endsection

resources/views/admin/colors/edit.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="main-panel">
        <!-- content-wrapper start -->
        <div class="content-wrapper">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="d-flex justify-content-between align-items-center">
                                <span class="text-uppercase">Edit Color</span>
                                <a href="{{route('colors.index')}}" class="btn btn-outline-secondary">BACK</a>
                            </h3>
                        </div>
                        <form method="POST" enctype="multipart/form-data" action="{{route('colors.update', $color->id)}}">
                            @csrf
                            @method('PUT')
                            <div class="card-body">
                                <div class="form-group mb-3">
                                    <label for="name">Color Name</label>
                                    <input class="form-control" id="name" name="name" value="{{old('name') ?? $color->name}}" autofocus>
                                    @error('name') <span class="text-danger">{{$message}}</span> @enderror
                                </div>

                                <div class="form-group mb-3">
                                    <label for="code">Color Code</label>
                                    <input class="form-control" id="code" name="code" value="{{old('code') ?? $color->code}}" autofocus>
                                    @error('code') <span class="text-danger">{{$message}}</span> @enderror
                                </div>

                                <div class="form-group mb-3">
                                    <label for="status">Status</label>
                                    <input type="checkbox" class="form-check" id="status" name="status" @checked($color->status) style="width: 30px;height: 30px;">
                                </div>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-outline-primary">UPDATE</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper end -->

        <!-- Start footer -->
        <footer class="footer">
            <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright ©
                <a href="https://www.bootstrapdash.com/" target="_blank">bootstrapdash.com </a>2021
            </span>
                <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Only the best
                <a href="https://www.bootstrapdash.com/" target="_blank"> Bootstrap dashboard  </a> templates
            </span>
            </div>
        </footer>
        <!-- End footer -->
    </div>
@endsection

resources/views/admin/colors/index.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="main-panel">
        <!-- content-wrapper start -->
        <div class="content-wrapper">
            <div class="row">
                <div class="col-12">
                    @if(session('message'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <strong>{{session('message')}}</strong>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    @endif
                </div>
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="d-flex justify-content-between align-items-center mb-0">
                                <span class="text-uppercase fw-bold">Color</span>
                                <a href="{{route('colors.create')}}" class="btn btn-sm btn-outline-primary">Add Color</a>
                            </h3>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-hover table-bordered">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Color Name</th>
                                            <th>Color Code</th>
                                            <th>Status</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse($colors as $color)
                                            <tr>
                                                <td>
                                                    {{$color->id}}
                                                </td>
                                                <td>
                                                    {{$color->name}}
                                                </td>
                                                <td>
                                                    {{$color->code}}
                                                </td>
                                                <td>
                                                    <span class="badge bg-primary">{{$color->status == 1 ? 'hidden' : 'visible'}}</span>
                                                </td>
                                                <td>
                                                    <a href="{{route('colors.edit', $color->id)}}" class="btn btn-sm btn-outline-warning"><i class="mdi mdi-pencil"></i></a>
                                                    <a href="{{route('colors.destroy', $color->id)}}" class="btn btn-sm btn-outline-danger" onclick="return confirm('Are you sure that you want to delete this data?')"><i class="mdi mdi-delete"></i></a>
                                                </td>
                                            </tr>
                                        @empty
                                            <tr>
                                                <td colspan="5">No colors in table</td>
                                            </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                            <div class="mt-4">
                                {{$colors->links()}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper end -->

        <!-- Start footer -->
        <footer class="footer">
            <div class="d-sm-flex justify-content-center justify-content-sm-between">
        <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright ©
            <a href="https://www.bootstrapdash.com/" target="_blank">bootstrapdash.com </a>2021
        </span>
                <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Only the best
            <a href="https://www.bootstrapdash.com/" target="_blank"> Bootstrap dashboard  </a> templates
        </span>
            </div>
        </footer>
        <!-- End footer -->
    </div>
@endsection