routes/web.php
<?php

use App\Http\Controllers\Admin\BannerController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ColorController;
use App\Http\Controllers\Admin\ConfigController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\SizeController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Shopping\CartController;
use App\Http\Controllers\Shopping\CheckoutController;
use App\Http\Controllers\Shopping\OrderController as SOC;
use App\Http\Controllers\Shopping\ShoppingController;
use App\Http\Controllers\Shopping\WishlistController;
use App\Http\Controllers\Shopping\UserController as SUC;
use App\Http\Livewire\Admin\Brand\Index;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\URL;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

if (App::environment('production')) {
    URL::forceScheme('https');
}

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::controller(ShoppingController::class)->group(function () {
    Route::get('/', 'index')->name('shopping');
    Route::get('/search', 'search')->name('search');
    Route::get('/category', 'category')->name('category');
    Route::get('/category/{slug}', 'catalogProduct')->name('category.product');
    Route::get('/product/{category}/{slug}', 'productDetail')->name('product.detail');
    Route::get('/trending-product', 'trendingProduct')->name('trending.product');
    Route::get('/new-arrival', 'newArrival')->name('new.arrival');
    Route::get('/featured-product', 'featuredProduct')->name('featured.product');
    Route::get('/thank-you', 'thankyou')->name('thank.you');
});

Route::middleware('auth')->group(function () {
    Route::get('/wishlist', [WishlistController::class, 'index'])->name('wishlist');
    Route::get('/cart', [CartController::class, 'index'])->name('cart');
    Route::get('/checkout', [CheckoutController::class, 'index'])->name('checkout');
    Route::get('/order', [SOC::class, 'index'])->name('order.index');
    Route::get('/order/{order}', [SOC::class, 'show'])->name('order.show');
    Route::get('/profile', [SUC::class, 'index'])->name('profile.index');
    Route::post('/profile', [SUC::class, 'store'])->name('profile.store');
    Route::get('/password', [SUC::class, 'show'])->name('password.create');
    Route::post('/password', [SUC::class, 'update'])->name('password.change');
});

Route::prefix('/admin')->middleware(['auth', 'isAdmin'])->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('admin.dashboard');

    Route::get('/brands', Index::class)->name('brands.index');

    Route::prefix('/configs')->controller(ConfigController::class)->name('configs.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::post('/store', 'store')->name('store');
    });

    Route::prefix('/orders')->controller(OrderController::class)->name('orders.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/{order}', 'show')->name('show');
        Route::put('/{order}', 'update')->name('update');
        Route::get('/invoice/show/{id}', 'display')->name('invoice.display');
        Route::get('/invoice/generate/{id}', 'generate')->name('invoice.generate');
        Route::get('/invoice/send/{id}', 'send')->name('invoice.send');
    });

    Route::prefix('/banners')->controller(BannerController::class)->name('banners.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/create', 'create')->name('create');
        Route::post('/store', 'store')->name('store');
        Route::get('/{banner}/edit', 'edit')->name('edit');
        Route::put('/{banner}/update', 'update')->name('update');
        Route::get('/{banner}/delete', 'destroy')->name('destroy');
    });

    Route::prefix('/categories')->controller(CategoryController::class)->name('categories.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/create', 'create')->name('create');
        Route::post('/store', 'store')->name('store');
        Route::get('/{category}/edit', 'edit')->name('edit');
        Route::put('/{category}/update', 'update')->name('update');
    });

    Route::prefix('/products')->controller(ProductController::class)->name('products.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/create', 'create')->name('create');
        Route::post('/store', 'store')->name('store');
        Route::get('/{product}/edit', 'edit')->name('edit');
        Route::put('/{product}/update', 'update')->name('update');
        Route::post('/{product}/color', 'updateColorQuantity')->name('updateColorQuantity');
        Route::post('/{product}/size', 'updateSizeQuantity')->name('updateSizeQuantity');
        Route::get('/{product}/color/delete', 'removeColor')->name('removeColor');
        Route::get('/{product}/size/delete', 'removeSize')->name('removeSize');
        Route::get('/{product}/image', 'remove')->name('remove');
        Route::get('/{product}/delete', 'destroy')->name('destroy');
    });

    Route::prefix('/colors')->controller(ColorController::class)->name('colors.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/create', 'create')->name('create');
        Route::post('/store', 'store')->name('store');
        Route::get('/{color}/edit', 'edit')->name('edit');
        Route::put('/{color}/update', 'update')->name('update');
        Route::get('/{color}/delete', 'destroy')->name('destroy');
    });

    Route::prefix('/sizes')->controller(SizeController::class)->name('sizes.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/create', 'create')->name('create');
        Route::post('/store', 'store')->name('store');
        Route::get('/{size}/edit', 'edit')->name('edit');
        Route::put('/{size}/update', 'update')->name('update');
        Route::get('/{size}/delete', 'destroy')->name('destroy');
    });

    Route::prefix('/users')->controller(UserController::class)->name('users.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/create', 'create')->name('create');
        Route::post('/store', 'store')->name('store');
        Route::get('/{user}/edit', 'edit')->name('edit');
        Route::put('/{user}/update', 'update')->name('update');
        Route::get('/{user}/delete', 'destroy')->name('destroy');
    });
});

app/Models/Category.php
<?php

namespace App\Models;

use App\Traits\HandleImageCatalog;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory, HandleImageCatalog;

    protected $table = 'categories';

    protected $fillable = [
        'name',
        'slug',
        'description',
        'image',
        'meta_title',
        'meta_keyword',
        'meta_description',
        'status'
    ];

    public function products()
    {
        return $this->hasMany(Product::class, 'category_id', 'id');
    }

    public function relatedProducts()
    {
        return $this->hasMany(Product::class, 'category_id', 'id')->latest();
    }

    public function brands()
    {
        return $this->hasMany(Brand::class, 'category_id', 'id')->where('status', '0');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Category\CategoryFormRequest;
use App\Models\Category;
use Illuminate\Support\Str;

class CategoryController extends Controller
{
    /**
     * @var Category $category
     */
    protected Category $category;

    /**
     * Create a new controller instance.
     *
     * @param Category $category
     */
    public function __construct(Category $category)
    {
        $this->category = $category;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
//        $categories = $this->category->latest('id')->all();
        return view('admin.categories.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  CategoryFormRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryFormRequest $request)
    {
        $dataCreated = $request->all();
        $dataCreated['slug'] = Str::slug($request->slug);
        $dataCreated['status'] = $request->status ? '1' : '0';
        $dataCreated['image'] = $this->category->saveImage($request);
        $this->category->create($dataCreated);
        return redirect()->route('categories.index')->with('message', 'Category added successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('admin.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  CategoryFormRequest  $request
     * @param  integer  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryFormRequest $request, int $id)
    {
        $dataUpdated = $request->all();
        $category = $this->category->findOrFail($id);
        $dataUpdated['slug'] = Str::slug($request->slug);
        $dataUpdated['status'] = $request->status ? '1' : '0';
        $dataUpdated['image'] = $this->category->updateImage($request, $category->image);
        $category->update($dataUpdated);
        return redirect()->route('categories.index')->with('message', 'Category '.$category->name.' updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
    }
}

app/Http/Livewire/Admin/Category/Index.php
<?php

namespace App\Http\Livewire\Admin\Category;

use App\Models\Category;
use Illuminate\Support\Facades\File;
use Livewire\Component;
use Livewire\WithPagination;

class Index extends Component
{
    public $category_id;

    public function deleteCategory($category_id)
    {
        $this->category_id = $category_id;
    }

    public function destroyCategory()
    {
        $category = Category::findOrFail($this->category_id);
        $path = 'upload/category'.$category->image;
        if (File::exists($path)) {
            File::delete($path);
        }
        $category->delete();
        session()->flash('message', 'Category deleted successfully!');
        $this->dispatchBrowserEvent('close-modal');
    }

    public function render()
    {
        $categories = Category::orderBy('id', 'desc')->paginate(5);
        return view('livewire.admin.category.index', compact('categories'));
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="main-panel">
        <!-- content-wrapper start -->
        <div class="content-wrapper">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="d-flex justify-content-between align-items-center">
                                <span class="text-uppercase">Add Category</span>
                                <a href="{{route('categories.index')}}" class="btn btn-outline-secondary">BACK</a>
                            </h3>
                        </div>
                        <form method="POST" enctype="multipart/form-data" action="{{route('categories.store')}}">
                            @csrf
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-6 form-group mb-3">
                                        <label for="name">Name</label>
                                        <input class="form-control" id="name" name="name" value="{{old('name')}}" autofocus>
                                        @error('name') <span class="text-danger">{{$message}}</span> @enderror
                                    </div>

                                    <div class="col-6 form-group mb-3">
                                        <label for="slug">Slug</label>
                                        <input class="form-control" id="slug" name="slug" value="{{old('slug')}}" autofocus>
                                        @error('slug') <span class="text-danger">{{$message}}</span> @enderror
                                    </div>

                                    <div class="col-12 form-group mb-3">
                                        <label for="description">Description</label>
                                        <textarea class="form-control" id="description" name="description" rows="3">{{old('description')}}</textarea>
                                        @error('description') <span class="text-danger">{{$message}}</span> @enderror
                                    </div>

                                    <div class="col-6 form-group mb-3">
                                        <label for="image">Image</label>
                                        <input type="file" class="form-control" id="image" name="image" value="{{old('image')}}">
                                        @error('image') <span class="text-danger">{{$message}}</span> @enderror
                                    </div>

                                    <div class="col-6 form-group mb-3">
                                        <label for="status">Status</label>
                                        <input type="checkbox" class="form-check" id="status" name="status">
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-12 my-3">
                                        <h4>SEO</h4>
                                    </div>

                                    <div class="col-6 form-group mb-3">
                                        <label for="meta_title">Meta title</label>
                                        <input type="text" class="form-control" id="meta_title" name="meta_title" value="{{old('meta_title')}}">
                                        @error('meta_title') <span class="text-danger">{{$message}}</span> @enderror
                                    </div>

                                    <div class="col-6 form-group mb-3">
                                        <label for="meta_keyword">Meta keyword</label>
                                        <input type="text" class="form-control" id="meta_keyword" name="meta_keyword" value="{{old('meta_keyword')}}">
                                        @error('meta_keyword') <span class="text-danger">{{$message}}</span> @enderror
                                    </div>

                                    <div class="col-12 form-group mb-3">
                                        <label for="meta_description">Meta description</label>
                                        <textarea class="form-control" id="meta_description" name="meta_description" rows="3">{{old('meta_description')}}</textarea>
                                        @error('meta_description') <span class="text-danger">{{$message}}</span> @enderror
                                    </div>
                                </div>

                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-outline-primary">SUBMIT</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper end -->

        <!-- Start footer -->
        <footer class="footer">
            <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright ©
                <a href="https://www.bootstrapdash.com/" target="_blank">bootstrapdash.com </a>2021
            </span>
                <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Only the best
                <a href="https://www.bootstrapdash.com/" target="_blank"> Bootstrap dashboard  </a> templates
            </span>
            </div>
        </footer>
        <!-- End footer -->
    </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="main-panel">
        <!-- content-wrapper start -->
        <div class="content-wrapper">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="d-flex justify-content-between align-items-center">
                                <span class="text-uppercase">Edit Category</span>
                                <a href="{{route('categories.index')}}" class="btn btn-outline-secondary">BACK</a>
                            </h3>
                        </div>
                        <form method="POST" enctype="multipart/form-data" action="{{route('categories.update', $category->id)}}">
                            @csrf
                            @method('PUT')
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-6 form-group mb-3">
                                        <label for="name">Name</label>
                                        <input class="form-control" id="name" name="name" value="{{old('name') ?? $category->name}}" autofocus>
                                        @error('name') <span class="text-danger">{{$message}}</span> @enderror
                                    </div>

                                    <div class="col-6 form-group mb-3">
                                        <label for="slug">Slug</label>
                                        <input class="form-control" id="slug" name="slug" value="{{old('slug') ?? $category->slug}}" autofocus>
                                        @error('slug') <span class="text-danger">{{$message}}</span> @enderror
                                    </div>

                                    <div class="col-12 form-group mb-3">
                                        <label for="description">Description</label>
                                        <textarea class="form-control" id="description" name="description" rows="3">{{old('description') ?? $category->description}}</textarea>
                                        @error('description') <span class="text-danger">{{$message}}</span> @enderror
                                    </div>

                                    <div class="col-6 form-group mb-3">
                                        <label for="image">Image</label>
                                        <input type="file" class="form-control" id="image" name="image" value="{{old('image') ?? $category->image}}">
                                        <img src="{{asset('upload/category/'.$category->image)}}" alt="{{$category->name}}" class="mt-3" width="60" height="60" />
                                        @error('image') <span class="text-danger">{{$message}}</span> @enderror
                                    </div>

                                    <div class="col-6 form-group mb-3">
                                        <label for="status">Status</label>
                                        <input type="checkbox" class="form-check" id="status" name="status" @checked($category->status == '1')>
                                    </div>
                                </div>


                                <div class="row">
                                    <div class="col-12 my-3">
                                        <h4>SEO</h4>
                                    </div>

                                    <div class="col-6 form-group mb-3">
                                        <label for="meta_title">Meta title</label>
                                        <input type="text" class="form-control" id="meta_title" name="meta_title" value="{{old('meta_title') ?? $category->meta_title}}">
                                        @error('meta_title') <span class="text-danger">{{$message}}</span> @enderror
                                    </div>

                                    <div class="col-6 form-group mb-3">
                                        <label for="meta_keyword">Meta keyword</label>
                                        <input type="text" class="form-control" id="meta_keyword" name="meta_keyword" value="{{old('meta_keyword') ?? $category->meta_keyword}}">
                                        @error('meta_keyword') <span class="text-danger">{{$message}}</span> @enderror
                                    </div>

                                    <div class="col-12 form-group mb-3">
                                        <label for="meta_description">Meta description</label>
                                        <textarea class="form-control" id="meta_description" name="meta_description" rows="3">{{old('meta_description') ?? $category->meta_description}}</textarea>
                                        @error('meta_description') <span class="text-danger">{{$message}}</span> @enderror
                                    </div>
                                </div>

                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-outline-primary">UPDATE</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper end -->

        <!-- Start footer -->
        <footer class="footer">
            <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright ©
                <a href="https://www.bootstrapdash.com/" target="_blank">bootstrapdash.com </a>2021
            </span>
                <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Only the best
                <a href="https://www.bootstrapdash.com/" target="_blank"> Bootstrap dashboard  </a> templates
            </span>
            </div>
        </footer>
        <!-- End footer -->
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.app')
@section('content')
    <livewire:admin.category.index />
@endsection